/* eslint-disable react/function-component-definition */
import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useState } from 'react';
import ButtonTemplate from '../../components/button-template';
import TextInput from '../../components/text-input';
//import ToggleButton from '../components/toggle-button';
//import ButtonTemplate from '../components/button-template';
//import TextInput from '../components/text-input';
import styles from '../../css/tutor/tutorLogin.module.css';
import validator from 'validator';
import isTecEmail from '../../helpers/tec-email';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>WEB PAE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Muchas Gracias por tu ayuda en esta primera etapa de testeo! :3</p>
      </main>
    </div>
  );
};

export default Home;
