/* eslint-disable react/function-component-definition */
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import ToggleButton from '../components/toggle-button';

const Home: NextPage = () => (
  <div>
    <div style={{ width: '150px', height: '150px' }}>
      <ToggleButton />
    </div>

    <Head>
      <title>WEB PAE</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <h1>
        Welcome to <a href="#">PAE</a>
        Data
      </h1>
    </main>
  </div>
);

export default Home;
// <ConfirmPopup url="http://www.google.com" />
