import DragAndDrop from '@/components/drag-and-drop';
import MyCalendar from '@/components/frontend-calendar-view';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useState } from 'react';
import ButtonTemplate from '../components/button-template';
import ToggleButton from '../components/toggle-button';
import styles from '../css/register.module.css';

const Prueba: NextPage = () => {

    const [eventObj, setEventObj] = useState([]);
       // funcion que cambia el color de la celda.
       const changeColorOfCell = (cell: any) => {
        cell.style.background = '#039BE5';
        cell.style.border = 'none';
      };
    // funcion que cambia el color de la celda.
    const resetColorOfCell = (cell: any) => {
        cell.style.background = 'none';
        cell.style.border = '1px solid #f1f1f1';
      };

      let dummyData = [{ period: 1, day_week: 3, hour: 12 }]

  return (
    <div>
      <Head>
        <title>WEB PAE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.mainContainer}>
        <DragAndDrop />
        </div>
      </main>
    </div>
  );
};

export default Prueba;
