import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import styles from '../../css/tutor/home.module.css';
import ImageCard from '../../components/image-card';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>WEB PAE</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <div className={styles.container}>
        <div className={styles.bar}></div>

        <div className={styles.right}>
          <div className={styles.top}>
            <h1 className="title">Inicio</h1>
          </div>
          <div className={styles.cards}>
            <div className={styles.card}>
              <ImageCard
                image="/images/student-login-image.jpg"
                description="Perfil"
              />
            </div>
            <div className={styles.card}>
              <ImageCard
                image="/images/tutor-login-image.jpg"
                description="Asesorías asignadas"
              />
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
);

export default Home;
