/* eslint-disable react/function-component-definition */
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

import ButtonTemplate from '../../components/button-template';
import ProgressBar from '../../components/progress-bar';
import RegisterStyle from '../../css/tutor/register.module.css';

const Home: NextPage = () => {
  //
  const [progressBarState, setProgressBarState] = React.useState(0);
  const max = 3;
  const min = 0;
  const back = () => {
    if (progressBarState > min) {
      setProgressBarState(progressBarState - 1);
    } else {
      setProgressBarState(progressBarState);
    }
  };

  const next = () => {
    if (progressBarState < max) {
      setProgressBarState(progressBarState + 1);
    } else {
      setProgressBarState(progressBarState);
    }
  };
  return (
    <div>
      {/*box*/}
      <div className={RegisterStyle.completed}>
        <div className={RegisterStyle.box}>
          <p className={RegisterStyle.per}> Completado </p>
          <div className={RegisterStyle.barDiv}>
            <ProgressBar progress={progressBarState} />
          </div>
          <p className={RegisterStyle.estatus}>
            {progressBarState} / {max}
          </p>
        </div>

        <div className={RegisterStyle.buttons}>
          <ButtonTemplate
            onClickFunction={back}
            color={'#DADADA'}
            text={'ANTERIOR'}
          />
          <ButtonTemplate
            onClickFunction={next}
            color={'#039BE5'}
            text={'SIGUIENTE'}
          />
        </div>
      </div>

      <Head>
        <title>WEB PAE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcome to <a href="#">PAE</a>
          Data
        </h1>
      </main>
    </div>
  );
};

export default Home;
//<ConfirmPopup url="http://www.google.com" />
