/* eslint-disable react/function-component-definition */
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

import ButtonTemplate from '../../components/button-template';
import ProgressBar from '../../components/progress-bar';
import handler from '../api/hello';

const Home: NextPage = () => {
  const [progressBarState, setProgressBarState] = React.useState(0);

  const back = () => {
    setProgressBarState(progressBarState - 1);
  };

  const next = () => {
    setProgressBarState(progressBarState + 1);
  };
  return (
    <div>
      <ProgressBar progress={progressBarState} />
      <button onClick={next}>Siguiente </button>
      <button onClick={back}>Anterior </button>
      <Head>
        <title>WEB PAE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcome to <a href="#">PAE</a>
          Data
        </h1>
      </main>
    </div>
  );
};

export default Home;
//<ConfirmPopup url="http://www.google.com" />
