// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next';

type Data = {
  subjectName: string
};

let data = [
    'VA1002 Unidades de formación del semestre de introducción',
    'A1004 Cultura visual y sonora',
    'AV1002B Técnicas y discursos fotográficos',
    'CO1001B Metodologías de investigación de factores humanos',
    'DL1022 Metodologías del pensamiento creativo',
    'EG1001 Optativa de matemáticas y ciencias',
    'EH1001B Inmersión y experimentación creativa',
    'AR1001B Representación formal del espacio',
    'AV1001B Narrativa audiovisual',
    'EG1002 Optativa de humanidades y bellas artes',
    'EH1008 Imaginarios culturales de México',
    'EH1009 Semiótica y narratologías contemporáneas',
    'H1001B Estructuras simbólicas en la imagen, la literatura y la música',
    'A2001B Pre-producción de cortometraje animado',
    'A2002B Producción de cortometraje animado',
    'A2012 Dibujo',
    'A2013 Historia de la animación',
    'A2014 Fundamentos de la animación',
    'EG1003 Optativa de ciencias sociales y del comportamiento',
    'VA1001B Tópico de exploración',
    'A2003B Arte conceptual',
    'A2004B Fundamentos de interacción',
    'A2005B Arte instalación',
    'A2015 Exploración de la forma',
    'A2016 Introducción al 3D',
    'EG1004 Optativa de liderazgo, emprendimiento e innovación',
    'EG1005 Optativa de ética y ciudadanía',
    'OP3070 Optativa de arte digital I',
    'OP3071 Optativa de arte digital II',
    'OP3072 Optativa de arte digital III',
    'OP3073 Optativa de arte digital IV',
    'OP3074 Optativa de arte digital V',
    'OP3075 Optativa de arte digital VI',
    'AT3001B Proyecto de arte digital',
    'VA3111 Tópicos I',
    'VA3112 Tópicos II',
    'VA3113 Tópicos III',
    'VA3114 Tópicos IV',
    'VA3115 Tópicos V',
    'VA3116 Tópicos VI',
    'AT3002B Proyecto integral de arte digital',
    'OP3001B Optativa profesional multidisciplinaria',
    'A1004 Cultura visual y sonora',
    'AR1001B Representación formal del espacio',
    'AV1001B Narrativa audiovisual',
    'AV1002B Técnicas y discursos fotográficos',
    'CO1001B Metodologías de investigación de factores humanos',
    'DL1022 Metodologías del pensamiento creativo',
    'EH1001B Inmersión y experimentación creativa',
    'EH1008 Imaginarios culturales de México',
    'EH1009 Semiótica y narratologías contemporáneas',
    'H1001B Estructuras simbólicas en la imagen, la literatura y la música',
    'A2001B Pre-producción de cortometraje animado',
    'A2002B Producción de cortometraje animado',
    'A2003B Arte conceptual',
    'A2004B Fundamentos de interacción',
    'A2005B Arte instalación',
    'A2012 Dibujo',
    'A2013 Historia de la animación',
    'A2014 Fundamentos de la animación',
    'A2015 Exploración de la forma',
    'A2016 Introducción al 3D',
    'AT3001B Proyecto de arte digital',
    'AT3002B Proyecto integral de arte digital',
    'OP3070 Optativa de arte digital I',
    'OP3071 Optativa de arte digital II',
    'OP3072 Optativa de arte digital III',
    'OP3073 Optativa de arte digital IV',
    'OP3074 Optativa de arte digital V',
    'OP3075 Optativa de arte digital VI',
    'EG1001 Optativa de matemáticas y ciencias',
    'EG1002 Optativa de humanidades y bellas artes',
    'EG1003 Optativa de ciencias sociales y del comportamiento',
    'EG1004 Optativa de liderazgo, emprendimiento e innovación',
    'EG1005 Optativa de ética y ciudadanía',
    'OP3001B Optativa profesional multidisciplinaria',
    'VA1001B Tópico de exploración',
    'VA3111 Tópicos I',
    'VA3112 Tópicos II',
    'VA3113 Tópicos III',
    'VA3114 Tópicos IV',
    'VA3115 Tópicos V',
    'VA3116 Tópicos VI',
    'VA1002 Unidades de formación del semestre de introducción',
    'VA1002 Introductory Courses',
    'A1004 Visual Sound and Culture',
    'AV1002B Photographic Techniques and Discourses',
    'CO1001B Human Factors Research Methodologies',
   'DL1022 Methodologies of Creative Thinking',
    'EG1001 Elective Course Mathematics and Science',
    'EH1001B Creative Immersion and Experimentation',
    'AR1001B Formal representation of space',
    'AV1001B Audiovisual Narrative',
    'EG1002 Elective Course Humanities and Fine Arts',
    'EH1008 Cultural Imaginaries of Mexico',
    'EH1009 Semiotics and Contemporary Narratologies',
    'H1001B Symbolic Structures in Image, Literature and Music',
    'A2001B Pre-Production of Animated Short Film',
    'A2002B Animated Short Film Production',
    'A2012 Drawing',
    'A2013 History of animation',
    'A2014 Fundamentals of Animation',
    'EG1003 Elective Course Social and Behavioral Sciences',
    'VA1001B Exploration Topic',
    'A2003B Conceptual Art',
    'A2004B Fundamentals of Interaction',
    'A2005B Installation Art',
    'A2015 Exploration of the Form',
    'A2016 Introduction to 3D',
    'EG1004 Elective Course Leadership, Entrepreneurship and Innovation',
    'EG1005 Elective Course Ethics and Citizenship',
    'OP3070 Elective Course Digital Art I',
    'OP3071 Elective Course Digital Art II',
    'OP3072 Elective Course Digital Art III',
    'OP3073 Elective Course Digital Art IV',
    'OP3074 Elective Course Digital Art V',
    'OP3075 Elective Course Digital Art VI',
    'AT3001B Digital Art Project',
    'VA3111 Elective I',
    'VA3112 Elective II',
    'VA3113 Elective III',
    'VA3114 Elective IV',
    'VA3115 Elective V',
    'VA3116 Elective VI',
    'AT3002B Comprehensive Digital Art Project',
    'OP3001B Elective Multidisciplinary Professional',
    'A1004 Visual Sound and Culture',
    'AR1001B Formal representation of space',
    'AV1001B Audiovisual Narrative',
    'AV1002B Photographic Techniques and Discourses',
    'CO1001B Human Factors Research Methodologies',
    'DL1022 Methodologies of Creative Thinking',
    'EH1001B Creative Immersion and Experimentation',
    'EH1008 Cultural Imaginaries of Mexico',
    'EH1009 Semiotics and Contemporary Narratologies',
    'H1001B Symbolic Structures in Image, Literature and Music',
    'A2001B Pre-Production of Animated Short Film',
    'A2002B Animated Short Film Production',
    'A2003B Conceptual Art',
    'A2004B Fundamentals of Interaction',
    'A2005B Installation Art',
    'A2012 Drawing',
    'A2013 History of animation',
    'A2014 Fundamentals of Animation',
    'A2015 Exploration of the Form',
    'A2016 Introduction to 3D',
    'AT3001B Digital Art Project',
    'AT3002B Comprehensive Digital Art Project',
    'OP3070 Elective Course Digital Art I',
    'OP3071 Elective Course Digital Art II',
    'OP3072 Elective Course Digital Art III',
    'OP3073 Elective Course Digital Art IV',
    'OP3074 Elective Course Digital Art V',
    'OP3075 Elective Course Digital Art VI',
    'EG1001 Elective Course Mathematics and Science',
    'EG1002 Elective Course Humanities and Fine Arts',
    'EG1003 Elective Course Social and Behavioral Sciences',
    'EG1004 Elective Course Leadership, Entrepreneurship and Innovation',
    'EG1005 Elective Course Ethics and Citizenship',
    'OP3001B Elective Multidisciplinary Professional',
    'VA1001B Exploration Topic',
    'VA3111 Elective I',
    'VA3112 Elective II',
    'VA3113 Elective III',
    'VA3114 Elective IV',
    'VA3115 Elective V',
    'VA3116 Elective VI',
    'VA1002 Introductory Courses',
];

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  res.status(200).json(data);
}
