/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable react/function-component-definition */
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import React, { useState } from 'react';
import { useForm, useFormState } from 'react-hook-form';
import styles from '../css/student/studentLogin.module.css';
import login from '../helpers/login';
import ButtonTemplate from './button-template';
import { LoginData, loginDefaultValues } from './login-input';
import TextInput from './text-input';

interface LoginFormProps {
  url: string;
  image: string;
  homeRoute: string;
  user: string;
  forgotPasswordRoute: string;
}

const LoginForm = ({
  url,
  image,
  homeRoute,
  user,
  forgotPasswordRoute
}: LoginFormProps) => {
  const [isLoading, setIsLoading] = useState(false);
  const router = useRouter();
  const {
    control,
    handleSubmit,
    formState: { errors }
  } = useForm<LoginData>({ defaultValues: loginDefaultValues });

  const { isDirty } = useFormState({ control });

  const onSubmit = handleSubmit((data) => {
    const formattedUser = `${user}${data.email.substring(0, 9)}`.toLowerCase();
    setIsLoading(true);
    console.log(formattedUser, data.password);
    login({ username: formattedUser, password: data.password }, url).then(
      ({ auth, message }) => {
        setIsLoading(false);
        if (auth) {
          router.push(homeRoute);
        } else {
          alert(message);
        }
      }
    );
  });

  return (
    <div>
      <Head>
        <title>Inicia sesión</title>
        <meta name="description" content="Generated by Hacket" />
        <link rel="icon" href="/images/icon.ico" />
      </Head>

      <main>
        <form className={styles.mainContainer} onSubmit={onSubmit}>
          <div className={styles.leftCont}>
            <img src={image} className={styles.loginImage} />
          </div>
          <div className={styles.signIn}>
            <div className={styles.paeLogin}>
              <img src="/images/pae-logo.png" className={styles.paeLogo} />
              <h1 className={styles.paeText}> PAE | LOGIN</h1>
            </div>
            <div className={styles.loginFields}>
              <div className={styles.component}>
                <TextInput
                  name="email"
                  placeholder="CORREO INSTITUCIONAL"
                  control={control}
                  error={errors.email}
                  rules={{
                    required: 'Matrícula requerida',
                    pattern: {
                      value: /^([A,a]{1}[0]{1}[0-9]{7}(@tec\.mx)*)/i,
                      message:
                        'Correo eléctronico inválido. E.g. A0XXXXXXX@tec.mx'
                    }
                  }}
                />
              </div>
              <div className={styles.component}>
                <TextInput
                  name="password"
                  type="password"
                  placeholder="CONTRASEÑA"
                  control={control}
                  error={errors.password}
                  rules={{
                    required: 'Contraseña requerida',
                    minLength: { value: 8, message: 'Contraseña muy corta' }
                  }}
                />
              </div>
              <div className={styles.componentB}>
                <ButtonTemplate
                  variant="primary"
                  type="submit"
                  disabled={!isDirty || isLoading}
                  loading={isLoading}
                >
                  INICIAR SESION
                </ButtonTemplate>
              </div>
            </div>
            <div className={styles.notUser}>
              <Link href={forgotPasswordRoute}>
                <a className={styles.forgotPassword}>Olvidé mi contraseña</a>
              </Link>
              <h2 className={styles.register}>
                ¿No tienes cuenta?{' '}
                <Link href="/register">
                  <a className={styles.regLink}>Regístrate</a>
                </Link>
              </h2>
              <a href="#" className={styles.privacy}>
                Aviso de privacidad
              </a>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
};

export default LoginForm;
