import sidebarStyles from '../css/components/sidebar.module.css';
import Link from 'next/link';
import { UrlObject } from 'url';

const SideBar = (props: {
  dashboardFunction: string | UrlObject;
  profileFunction: string | UrlObject;
  tutoringFunction: string | UrlObject;
  calendarText: string;
}) => {
  return (
    <div className={sidebarStyles.main}>
      <div className={sidebarStyles.normal}>
        <Link href="#">
          <div className={sidebarStyles.pae}>
            <img src="/images/pae-logo.png" className={sidebarStyles.logoPae} />
            <p className={sidebarStyles.textPae}>PAE</p>
          </div>
        </Link>
        <Link href={props.dashboardFunction}>
          <div className={sidebarStyles.dashboard} id="target1">
            <img
              src="/icons/house-door.svg"
              className={sidebarStyles.dbImage}
            ></img>
            <p className={sidebarStyles.dbText}>Dashboard</p>
          </div>
        </Link>
        <Link href={props.profileFunction}>
          <div className={sidebarStyles.dashboard}>
            <img
              src="/icons/person-circle.svg"
              className={sidebarStyles.dbImage}
            ></img>
            <p className={sidebarStyles.dbText}>Perfil</p>
          </div>
        </Link>
        <Link href={props.tutoringFunction}>
          <div className={sidebarStyles.dashboard}>
            <img
              src="/icons/calendar-week.svg"
              className={sidebarStyles.dbImage}
            ></img>
            <p className={sidebarStyles.dbText}>{props.calendarText}</p>
          </div>
        </Link>
        <Link href="/../student/login">
          <div className={sidebarStyles.exit}>
            <img
              className={sidebarStyles.exitImage}
              src="/icons/arrow-bar-right.svg"
            />
          </div>
        </Link>
      </div>
      <div className={sidebarStyles.hamburgerMenu}>
        <input type="checkbox" className={sidebarStyles.toggler} />
        <div className={sidebarStyles.hamburger}>
          <div></div>
        </div>
        <div className={sidebarStyles.menu}>
          <div>
            <ul>
              <li>
                <Link href="#">
                  <div className={sidebarStyles.pae}>
                    <img
                      src="/images/pae-logo.png"
                      className={sidebarStyles.logoPae}
                    />
                    <p className={sidebarStyles.textPae}>PAE</p>
                  </div>
                </Link>
              </li>
              <li>
                <Link href={props.dashboardFunction}>
                  <div className={sidebarStyles.dashboard}>
                    <img
                      src="/icons/house-door.svg"
                      className={sidebarStyles.dbImage}
                    ></img>
                    <p className={sidebarStyles.dbText}>Dashboard</p>
                  </div>
                </Link>
              </li>
              <li>
                <Link href={props.profileFunction}>
                  <div className={sidebarStyles.dashboard}>
                    <img
                      src="/icons/person-circle.svg"
                      className={sidebarStyles.dbImage}
                    ></img>
                    <p className={sidebarStyles.dbText}>Perfil</p>
                  </div>
                </Link>
              </li>
              <li>
                <Link href={props.tutoringFunction}>
                  <div className={sidebarStyles.dashboard}>
                    <img
                      src="/icons/calendar-week.svg"
                      className={sidebarStyles.dbImage}
                    ></img>
                    <p className={sidebarStyles.dbText}>{props.calendarText}</p>
                  </div>
                </Link>
              </li>
              <li>
                <Link href="/../student/login">
                  <div className={sidebarStyles.exit}>
                    <img
                      className={sidebarStyles.exitImage}
                      src="/icons/arrow-bar-right.svg"
                    />
                  </div>
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};
/*
  Ejemplo de pantalla 
  HTML:
  <div>
    <Head>
      <title>WEB PAE</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={indexStyles.main}>
      <div className={indexStyles.sidebar}>
        <SideBar
          dashboardFunction="#"
          profileFunction="/../student/login"
          tutoringFunction="/../student/login"
          calendarText="Agendar Asesoría"
        />
      </div>
      <div className={indexStyles.test}> Este es como si fuera tu nuevo main, o tu body, es todo el espacio que tienes para poner lo de tu pantalla
        <InputTextArea /> 
      </div>
    </main>
  </div>

  CSS:
    .main {
      display: flex;
      flex-direction: row;
    }

    .sidebar {
      height: 100%;
      width: 10%;
    }
    
    .test {
      width: 70vw;
      height: 20vw;
    }
    
    @media screen and (max-width: 800px) {
      .test {
        width: 45vw;
        height: 45vw;
      }
    }

*/
export default SideBar;
