/* eslint-disable jsx-a11y/alt-text */
import Link from 'next/link';
import React from 'react';
import sidebarStyles from '../css/components/sidebar.module.css';

interface SideBarProps {
  routing: {
    routes: {
      path: string;
      icon: string;
      title: string;
    }[];
    exit: string;
  };
  currentRoute: string;
}

const SideBar = ({ routing, currentRoute }: SideBarProps) => (
  <div className={sidebarStyles.main}>
    <div className={sidebarStyles.normal}>
      <Link href="#" passHref>
        <div className={sidebarStyles.pae}>
          <img src="/images/pae-logo.png" className={sidebarStyles.logoPae} />
          <p className={sidebarStyles.textPae}>PAE</p>
        </div>
      </Link>
      {routing.routes.map((route) => (
        <Link href={route.path} passHref key={`${route.title}`}>
          <div
            className={sidebarStyles.dashboard}
            style={
              currentRoute === route.path
                ? { backgroundColor: 'white', color: '#0277BD' }
                : {}
            }
          >
            <div className={sidebarStyles.dbImage}>
              <i className={`bi bi-${route.icon}`} />
            </div>
            <p className={sidebarStyles.dbText}>{route.title}</p>
          </div>
        </Link>
      ))}

      <Link href={routing.exit} passHref>
        <div className={sidebarStyles.exit}>
          <i className="bi bi-arrow-bar-right" />
        </div>
      </Link>
    </div>
    <div className={sidebarStyles.hamburgerMenu}>
      <input type="checkbox" className={sidebarStyles.toggler} />
      <div className={sidebarStyles.hamburger}>
        <div />
      </div>
      <div className={sidebarStyles.menu}>
        <div>
          <ul>
            <li>
              <Link href="#" passHref>
                <div className={sidebarStyles.pae}>
                  <img
                    src="/images/pae-logo.png"
                    className={sidebarStyles.logoPae}
                  />
                  <p className={sidebarStyles.textPae}>PAE</p>
                </div>
              </Link>
            </li>
            {routing.routes.map((route) => (
              <li key={`${route.title}`}>
                <Link href={route.path} passHref>
                  <div
                    className={sidebarStyles.dashboard}
                    style={
                      currentRoute === route.path
                        ? { backgroundColor: 'white', color: '#0277BD' }
                        : {}
                    }
                  >
                    <div className={sidebarStyles.dbImage}>
                      <i className={`bi bi-${route.icon}`} />
                    </div>
                    <p className={sidebarStyles.dbText}>{route.title}</p>
                  </div>
                </Link>
              </li>
            ))}

            <li>
              <Link href={routing.exit} passHref>
                <div className={sidebarStyles.exit}>
                  <i className="bi bi-arrow-bar-right" />
                </div>
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
);
/*
  Ejemplo de pantalla 
  HTML:
  <div>
    <Head>
      <title>WEB PAE</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={indexStyles.main}>
      <div className={indexStyles.sidebar}>
        <SideBar
          dashboardFunction="#"
          profileFunction="/../student/login"
          tutoringFunction="/../student/login"
          calendarText="Agendar Asesoría"
        />
      </div>
      <div className={indexStyles.test}> Este es como si fuera tu nuevo main, o tu body, es todo el espacio que tienes para poner lo de tu pantalla
        <InputTextArea /> 
      </div>
    </main>
  </div>

  CSS:
    .main {
      display: flex;
      flex-direction: row;
    }

    .sidebar {
      height: 100%;
      width: 10%;
    }
    
    .test {
      width: 70vw;
      height: 20vw;
    }
    
    @media screen and (max-width: 800px) {
      .test {
        width: 45vw;
        height: 45vw;
      }
    }

*/
export default SideBar;
