# Generated by Django 4.0.4 on 2022-04-24 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_completedhours_tutor_completed_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
