# Generated by Django 4.0.4 on 2022-04-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_tutee_user_is_tutor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutee',
            old_name='tutee',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='tutor',
            new_name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
