import Head from 'next/head';
import React from 'react';
import styles from '../../css/hacket/developers.module.css';

const Developers = () => {
  return (
    <div className={styles.page}>
      <Head>
        <title>WEB PAE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.left}>
        <div className={styles.content}>
          <h1 className={styles.title}>Desarrolladores</h1>
          <span className={styles.name}>
            {' '}
            · Salvador Alejandro Gaytán Ibáñez{' '}
          </span>
          <span className={styles.name}> · Bryan González Arellano </span>
          <span className={styles.name}> · Alejandro Castro Reus </span>
          <span className={styles.name}> · José Antonio Bobadilla García </span>
          <span className={styles.name}> · Karen Rugerio Armenta </span>
        </div>
      </div>
      <div className={styles.right}>
        <div className={styles.imageContainer}>
          <img className={styles.teamImage} src="/images/landing.jpeg" />
        </div>
      </div>
    </div>
  );
};

export default Developers;
